<?php
session_start();
    if(!isset($_COOKIE['logstatus'])){
        header('location:../login.php');
    }
    $opt=$_POST['admOpt'];
    $chc=$_POST[$opt];

    echo $opt.$chc;
    if($chc=="addemployee"){
         header('location:../../views/admindashboards/addemployee.php');
    }elseif($chc=="updateinformation"){
        header('location:updateinformation.php');
    }elseif($chc=="employeedetails"){
        header('location:employeedetails.php');
    }elseif($chc=="adduser"){
        header('location:adduser.php');
    }elseif($chc=="updatedetails"){
        header('location:updatedetails.php');
    }elseif($chc=="addnewfacility"){
        header('location:addnewfacility.php');
    }elseif($chc=="updatefacility"){
        header('location:updatefacility.php');
    }elseif($chc=="addnewbranch"){
        header('location:addnewbranch.php');
    }elseif($chc=="branchdetails"){
        header('location:branchdetails.php');
    }elseif($chc=="addnewroom"){
        header('location:addnewroom.php');
    }elseif($chc=="updateroomfacilityy"){
        header('location:updateroomfacility.php');
    }elseif($chc=="totalrevenue"){
        header('location:totalrevenue.php');
    }
?>